name: Pipeline to build from the-code-repo

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build-the-code-repo:
    runs-on: ubuntu-latest
    steps:
      # Checks-out the pipeline repository
      - name: Checking out Repo 1 (self) and saving it to the-controller-repo directory 
        uses: actions/checkout@v2
        with:
          path: the-controller-repo 
      
      # Checks-out your code repository
      - name: Checking out another repo and saving it to the-tester-repo directory 
        uses: actions/checkout@v2
        with:
          repository: rohitnb/the-tester-repo
          path: the-tester-repo
          token: '${{secrets.GH_PAT}}'
          # ssh-key: '${{secrets.ORG_SSHKEY}}'
          
      # Runs a set of commands using the runners shell
      - name: Running commands
        run: |
          ls -lah
          pwd
          cd the-controller-repo
          ls -lah
          pwd
          cd ../the-tester-repo
          ls -lah
          pwd
